# Copyright 2019 Anatole Tresch
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: "Set hostname and /etc/hosts entries"
  hosts: "all"
  tasks:
    - name: "Set node hostname, aliases and other node/master servers..."
      include_role:
        name: "ahuffman.hosts"
      vars:
        hosts_backup: False
        hosts_set_hostname: True
        hosts_add_hosts:
          - hostname: "worker1"
            domain: "kubecluster.local"
            comment: 'The worker node'
          - name: "api"
            hostname: "master1"
            domain: "kubecluster.local"
            ip_addr: "192.168.50.2"
            comment: "Master server 1"
          - name: "api2"
            hostname: "master2"
            domain: "kubecluster.local"
            ip_addr: "192.168.50.2"
            comment: "Master server 1"
        hosts_hostname:
          hostname: "worker1"
          domain: "kubecluster.local"
          alias_loopback: False # Don't modify localhost loopback in /etc/hosts
          add_ips:
            - "192.168.50.10" # main NIC
          ipv6: False # Don't create ipv6 loopback entries 
